// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	Auth
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Auth_CertificateType int32

const (
	Auth_UUID     Auth_CertificateType = 0
	Auth_PLAIN    Auth_CertificateType = 1
	Auth_TOKEN    Auth_CertificateType = 2
	Auth_FACEBOOK Auth_CertificateType = 3
)

var Auth_CertificateType_name = map[int32]string{
	0: "UUID",
	1: "PLAIN",
	2: "TOKEN",
	3: "FACEBOOK",
}
var Auth_CertificateType_value = map[string]int32{
	"UUID":     0,
	"PLAIN":    1,
	"TOKEN":    2,
	"FACEBOOK": 3,
}

func (x Auth_CertificateType) String() string {
	return proto1.EnumName(Auth_CertificateType_name, int32(x))
}
func (Auth_CertificateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Auth struct {
}

func (m *Auth) Reset()                    { *m = Auth{} }
func (m *Auth) String() string            { return proto1.CompactTextString(m) }
func (*Auth) ProtoMessage()               {}
func (*Auth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Auth_Certificate struct {
	Type  Auth_CertificateType `protobuf:"varint,1,opt,name=Type,enum=proto.Auth_CertificateType" json:"Type,omitempty"`
	Proof []byte               `protobuf:"bytes,2,opt,name=Proof,proto3" json:"Proof,omitempty"`
}

func (m *Auth_Certificate) Reset()                    { *m = Auth_Certificate{} }
func (m *Auth_Certificate) String() string            { return proto1.CompactTextString(m) }
func (*Auth_Certificate) ProtoMessage()               {}
func (*Auth_Certificate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Auth_Result struct {
	OK     bool   `protobuf:"varint,1,opt,name=OK" json:"OK,omitempty"`
	UserId int32  `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	Body   []byte `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (m *Auth_Result) Reset()                    { *m = Auth_Result{} }
func (m *Auth_Result) String() string            { return proto1.CompactTextString(m) }
func (*Auth_Result) ProtoMessage()               {}
func (*Auth_Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func init() {
	proto1.RegisterType((*Auth)(nil), "proto.Auth")
	proto1.RegisterType((*Auth_Certificate)(nil), "proto.Auth.Certificate")
	proto1.RegisterType((*Auth_Result)(nil), "proto.Auth.Result")
	proto1.RegisterEnum("proto.Auth_CertificateType", Auth_CertificateType_name, Auth_CertificateType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for AuthService service

type AuthServiceClient interface {
	Auth(ctx context.Context, in *Auth_Certificate, opts ...grpc.CallOption) (*Auth_Result, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Auth(ctx context.Context, in *Auth_Certificate, opts ...grpc.CallOption) (*Auth_Result, error) {
	out := new(Auth_Result)
	err := grpc.Invoke(ctx, "/proto.AuthService/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	Auth(context.Context, *Auth_Certificate) (*Auth_Result, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth_Certificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Auth(ctx, req.(*Auth_Certificate))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x47, 0x18, 0xb9, 0x58, 0x1c,
	0x4b, 0x4b, 0x32, 0xa4, 0xdc, 0xb9, 0xb8, 0x9d, 0x53, 0x8b, 0x4a, 0x32, 0xd3, 0x32, 0x93, 0x13,
	0x4b, 0x52, 0x85, 0x34, 0xb9, 0x58, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8,
	0x8c, 0xa4, 0x21, 0x9a, 0xf4, 0x40, 0x2a, 0xf5, 0x90, 0x94, 0x81, 0x94, 0x08, 0xf1, 0x72, 0xb1,
	0x06, 0x14, 0xe5, 0xe7, 0xa7, 0x49, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x48, 0x19, 0x71, 0xb1, 0x05,
	0xa5, 0x16, 0x97, 0xe6, 0x94, 0x08, 0x71, 0x71, 0x31, 0xf9, 0x7b, 0x83, 0x4d, 0xe0, 0x10, 0xe2,
	0xe3, 0x62, 0x0b, 0x2d, 0x4e, 0x2d, 0xf2, 0x4c, 0x01, 0xab, 0x62, 0x15, 0xe2, 0xe1, 0x62, 0x71,
	0xca, 0x4f, 0xa9, 0x94, 0x60, 0x06, 0xe9, 0x51, 0xb2, 0xe7, 0xe2, 0x47, 0x37, 0x95, 0x83, 0x8b,
	0x25, 0x34, 0xd4, 0xd3, 0x45, 0x80, 0x41, 0x88, 0x93, 0x8b, 0x35, 0xc0, 0xc7, 0xd1, 0xd3, 0x4f,
	0x80, 0x11, 0xc4, 0x0c, 0xf1, 0xf7, 0x76, 0xf5, 0x13, 0x60, 0x12, 0xe2, 0xe1, 0xe2, 0x70, 0x73,
	0x74, 0x76, 0x75, 0xf2, 0xf7, 0xf7, 0x16, 0x60, 0x36, 0x72, 0xe1, 0xe2, 0x06, 0xb9, 0x2d, 0x38,
	0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x14, 0xe2, 0x29, 0x21, 0x71, 0x1c, 0xee, 0x96, 0x12,
	0x42, 0x96, 0x80, 0x38, 0x57, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xa2, 0x22, 0x0b, 0x19, 0x28, 0x01, 0x00, 0x00,
}
